### ISSUE TITLE
tutorial assumes $GOPATH="$HOME"/go

### ISSUE THREAD

**Issue by hxrts** [ixoworld/bonds#24]
Manually setting `$GOPATH` to `~/go` used to be the prescribed way to develop go programs, however development in an arbitrary directory using `go mod` now seems to be the preferred wisdom.

https://insujang.github.io/2020-04-04/go-modules/

https://blog.golang.org/migrating-to-go-modules

I think you should note that this tutorial assumes `$GOPATH` is set for now. In the long run we should be consistent with the [SDK tutorials](https://github.com/cosmos/sdk-tutorials), some of which also likely need an update.

cc @okwme @fadeev

**Comment by migueldingli1997** [comment]
Thank you @hxrts especially for the links.

I've applied what I think is the only change that was required. The project in general was already using `GO111MODULE=on` (in the Makefile) so it was just a matter of fixing the `clean_build.sh` script (unless I'm missing something hehe :angel:)

**Comment by hxrts** [comment]
I was getting an error with clean_build.sh until I changed, yes. sorry, should have mentioned.

**Comment by hxrts** [comment]
Just tried again, I think you maybe want to remove line 6 in `clean_build.sh` which moves up to the parent directory `cd ../`. When I run `make run_with_data` in the bonds root directory, this allows it to work without issue.

**Comment by migueldingli1997** [comment]
Ah that's right @hxrts

**Comment by migueldingli1997** [comment]
Thanks again!
